export const restaurantTypes = {
    RESTAURANT_GET: 'RESTAURANT_GET',
    RESTAURANT_FILTERED: 'RESTAURANT_FILTERED',
    RESTAURANT_ADD: 'RESTAURANT_ADD', 
    RESTAURANT_DELETE: 'RESTAURANT_DELETE' 
}

export const foodTypes = {
    FOOD_GET: 'FOOD_GET',
    FOOD_FILTERED: 'FOOD_FILTERED',
    FOOD_BUTTON: 'FOOD_BUTTON'
}